{
 "title": "LRSPipe",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Statements & Attachments Transferred",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "xapipe_statements_total" },
    { "expr": "xapipe_attachments_total" }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "xapipe_source_errors_total" },
    { "expr": "xapipe_target_errors_total" },
    { "expr": "xapipe_job_errors_total" }
   ]
  },
  {
   "title": "Statements Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(xapipe_statements_total[1m])"
    }
   ]
  },
  {
   "title": "Source & Target Request Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(xapipe_source_request_time_bucket[5m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(xapipe_target_request_time_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}