name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        target: [test-lib]
    runs-on: ubuntu-latest
    steps:
      - name: Setup CI Environment
        uses: yetanalytics/actions/setup-env@v0
      - name: Cache Deps
        uses: actions/cache@v2
        with:
          path: |
            .cpcache
          key: ${{ runner.os }}-${{ hashFiles('deps.edn') }}
      - name: Run make target ${{ matrix.target }}
        run: make ${{ matrix.target }}
