name: Periodic Vulnerability Scan

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  nvd_scan:
    uses: yetanalytics/actions/.github/workflows/nvd-scan.yml@fafd15d2735f4e58c8fa2f0d578f1b039a1f8867
    with:
      classpath-command: 'clojure -Spath -A:cli'
