name: Release

# Draft Release on any tag
on:
  push:
    tags:
      - 'v*'

jobs:
  get_modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: List Java modules
        id: echo-modules
        run: echo "modules=$(cat .java_modules)" >> $GITHUB_OUTPUT

    outputs:
      modules: ${{ steps.echo-modules.outputs.modules }}
  
  build_jre:
    needs: get_modules
    uses: yetanalytics/workflow-runtimer/.github/workflows/runtimer.yml@v2
    with:
      java-version: '11'
      java-distribution: 'temurin'
      java-modules: ${{ needs.get_modules.outputs.modules }}
  
  build:
    needs: build_jre
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Get an env
        uses: yetanalytics/actions/setup-env@v0.0.4

      - name: Cache Deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-
      - name: Build Xapipe
        run: make bundle BUNDLE_RUNTIMES=false

      - name: Download ubuntu-latest Artifact
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-22.04-jre

      - name: Download macOS-latest Artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-14-jre

      - name: Download windows-latest Artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-2022-jre

      - name: Unzip the runtimes
        run: |
          mkdir -p target/bundle/runtimes
          unzip ubuntu-22.04-jre.zip -d target/bundle/runtimes
          mv target/bundle/runtimes/ubuntu-22.04 target/bundle/runtimes/linux
          unzip macos-14-jre.zip -d target/bundle/runtimes
          mv target/bundle/runtimes/macos-14 target/bundle/runtimes/macos
          unzip windows-2022-jre.zip -d target/bundle/runtimes
          mv target/bundle/runtimes/windows-2022 target/bundle/runtimes/windows

      - name: Zip the bundle
        run: |
          cd target/bundle
          zip -r ../../xapipe.zip ./

      - name: Craft Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: 'xapipe.zip'

      - name: Deploy Documentation (Tag Pushes)
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: target/bundle/doc
