name: Release

# Draft Release on any tag
on:
  push:
    tags:
      - '*'

jobs:
  build_jre:
    uses: yetanalytics/runtimer/.github/workflows/runtimer.yml@cf8c77d465f08962cd7901005b8cf197a6149ac1
    with:
      java-version: '11'
      java-distribution: 'temurin'
      java-modules: 'java.base,java.logging,java.naming,java.sql'

  build:
    needs: build_jre
    runs-on: ubuntu-latest
    steps:
      - name: Get an env
        uses: yetanalytics/actions/setup-env@v0

      - name: Cache Deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-cljdeps-
      - name: Build Xapipe
        run: make bundle BUNDLE_RUNTIMES=false

      - name: Download ubuntu-latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-20.04-jre

      - name: Download macOS-latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-10.15-jre

      - name: Download windows-latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-2019-jre

      - name: Unzip the runtimes
        run: |
          mkdir -p target/bundle/runtimes
          unzip ubuntu-20.04-jre.zip -d target/bundle/runtimes
          unzip macos-10.15-jre.zip -d target/bundle/runtimes
          unzip windows-2019-jre.zip -d target/bundle/runtimes

      - name: Zip the bundle
        run: |
          cd target/bundle
          zip -r ../../xapipe.zip ./

      - name: Craft Draft Release
        uses: softprops/action-gh-release@v1
        with:
          body: "## Release Notes\nTODO: Create great release notes!"
          draft: true
          files: 'xapipe.zip'
